### ISSUE TITLE
DbContext Dispose not works

### ISSUE THREAD

**Issue by superarchi** [morrisjdev/FileContextCore#18]
After disposing of the first context, the second contains the same data.

Example:
```cs
using (var context = new Context())
{
    context.Users.Add(new User());
    context.SaveChanges();
}

Directory.Delete(Path.Combine(AppContext.BaseDirectory, "appdata"), true);

using (var context = new Context())
{
    var u1 = context.Users.First();
}
```
I expected exception here

**Comment by morrisjdev** [comment]
Hi.
Sorry for the late reply.

You are right. This is because FileContext stores the data in memory after the initial load. It then writes everything back to disc if anything changes. The cache is shared between multiple instaces of the DbContext. This is reason for the discovered behavior.

Do you have any problems with that behavior?
