### ISSUE TITLE
EF scaffolding

### ISSUE THREAD

**Issue by NickStrupat** [morrisjdev/FileContextCore#2]
Have you considered supporting scaffolding (aka reverse-engineering)?

It would be cool to be able to run

`dotnet ef dbcontext scaffold "Data Source=file.xls" FileContextCore`

and get a `DbContext` and the entity classes for the file so it can be accessed with LINQ-to-Entites

**Comment by morrisjdev** [comment]
Sorry for the late reply. I also thought about this feature but I came to the result that this feature is not so useful. 

First the types in a simple document or an excel sheet are not so easy to convert so that your generated result will not be very useful. Also the idea of filecontext is to easy design entities in code and run the application without the need of migrations.
