### ISSUE TITLE
Is the database method able to support high concurrent user traffic for read/write?

### ISSUE THREAD

**Issue by Smilefounder** [morrisjdev/FileContextCore#29]
Hi @morrisjdev 

I love the idea! Is the database method able to support high concurrent user traffic (maximum database concurrent connections) for read/write files?

Best regards,
Huy

**Comment by morrisjdev** [comment]
Hi.

I don't think so.

A small to medium number of concurrent operations is possible because the database primary operates in memory, means the whole dataset of a table is loaded once one entry of a table is queried. This makes it possible to support multiple operations at a time. The storing in files is a next step and will always store the whole dataset if something was changed. This involves a new problem: For huge amounts of data or operations this will introduce massive I/O loads on the disk.

So all in all I wouldn't recommend that.

Best regards
Morris

**Comment by Smilefounder** [comment]
I see, thanks for the explanation 👍 

Best regards,
Huy
